name: shell commnands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello!!!"
      - name: multiline script
        run: | 
          node -v
          npm -v
      - name: python commnands
        run: |
          import platform
          print(platform.processor())
        shell: python
        
        